management:
  endpoints:
    web:
      exposure:
        include: info,health,beans,shutdown,loggers,prometheus
      path-mapping:
        prometheus: metrics
      metrics:
        enabled: true
      prometheus:
        enabled: true
  endpoint:
    health:
      show-components: always
      show-details: always
    shutdown:
      enabled: true
    loggers:
      enabled: true

resilience4j:
  retry:
    retry-aspect-order: 100
    instances:
      middleware-application-service-retry:
        max-attempts: 3
        wait-duration: 3s
        ignoreExceptions:
          - feign.FeignException.FeignClientException
        retryExceptions:
          - feign.FeignException.FeignServerException
          - feign.RetryableException
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      middleware-api-cb:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-type: count-based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 50s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
        ignoreExceptions:
          - feign.FeignException.FeignClientException
        recordExceptions:
          - feign.FeignException.FeignServerException
          - feign.RetryableException
      middleware-application-service-cb:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-type: count-based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 30s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
        ignoreExceptions:
          - feign.FeignException.FeignClientException
        recordExceptions:
          - feign.FeignException.FeignServerException
          - feign.RetryableException

kafka:
  enable: true

feign:
  client:
    config:
      default:
        connectTimeout: 90000
        readTimeout: 90000
        loggerLevel: full