management:
  endpoints:
    web:
      exposure:
        include: info,health,beans,shutdown,loggers,prometheus
      path-mapping:
        prometheus: metrics
      metrics:
        enabled: true
      prometheus:
        enabled: true
  endpoint:
    health:
      show-components: always
      show-details: always
    shutdown:
      enabled: true
    loggers:
      enabled: true

resilience4j:
  retry:
    retry-aspect-order: 100
    instances:
      middleware-application-service-retry:
        max-attempts: 3
        wait-duration: 3s
        ignoreExceptions:
          - feign.FeignException.FeignClientException
        retryExceptions:
          - feign.FeignException.FeignServerException
          - feign.RetryableException
      middleware-qq-api-retry:
        max-attempts: 3
        wait-duration: 100ms
        retryExceptions:
          - feign.RetryableException
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      middleware-api-cb:
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 10
        sliding-window-type: count-based
        sliding-window-size: 15
        minimum-number-of-calls: 10
        slow-call-duration-threshold: 60s
        slow-call-rate-threshold: 80
        failure-rate-threshold: 60
        record-failure-predicate: com.selina.lending.repository.circuitbreaker.RecordExceptionPredicate
      middleware-application-service-cb:
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 10
        sliding-window-type: count-based
        sliding-window-size: 15
        minimum-number-of-calls: 10
        slow-call-duration-threshold: 30s
        slow-call-rate-threshold: 80
        failure-rate-threshold: 60
        record-failure-predicate: com.selina.lending.repository.circuitbreaker.RecordExceptionPredicate

sentry:
  dsn: https://9337eb592bbe4bf592ad884470f4b4cd@sentry-everton.selinadev.co.uk/38
  traces-sample-rate: 1.0

kafka:
  enable: true
authorization:
  enable: true

feign:
  client:
    config:
      default:
        connectTimeout: 90000
        readTimeout: 180000
        loggerLevel: full
      middleware-qq-api:
        connectTimeout: 1000
        readTimeout: 2000
        loggerLevel: full
      eligibility-api:
        connectTimeout: 1000
        readTimeout: 5000
        loggerLevel: full

features:
  filterResponseOffers:
    enabled: false

sla:
  requests:
    - name: create Quick Quote application
      httpMethod: POST
      urlPattern: /application/quickquote
      timeout: 7500