server:
  servlet:
    context-path : /lending

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO;
        cache: TRACE;

management:
  endpoints:
    web:
      exposure:
        include: info,health,beans,shutdown,loggers,metrics,prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      show-components: always
      show-details: always
    shutdown:
      enabled: true
    loggers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      middleware-api-cb:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 1s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60

middleware:
  api:
    url: http://TBC

spring.security.oauth2.client:
  registration:
    #Repeat block for any number of AuthZ servers
    bar-auth: #unique supplier service name
      client-id: DUMMY_CLIENT_ID_XXX
      client-secret: DUMMY_CLIENT_SECRET_YYYY
      authorization-grant-type: client_credentials
      client-authentication-method: post
  provider:
    #Repeat block for any number of AuthZ servers
    bar-auth:
      token-uri: ${BAR_AUTH_SERVER_URI}/oauth/token
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:9999/realms/brokers
