apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ms-readonly-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - pods
  - services
  verbs:
  - get
  - watch
  - list